#!/bin/bash
#
# Bike Power Tracker - Cloudflare Tunnel Setup Script
# Helps configure Cloudflare Tunnel for secure remote access
#
# Usage: ./setup-cloudflare.sh
#

set -e

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_DIR="${SERVICE_DIR:-$(dirname "$SCRIPT_DIR")}"
CLOUDFLARED_CONFIG_DIR="${HOME}/.cloudflared"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

print_header() {
    echo ""
    echo -e "${BLUE}=====================================${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}=====================================${NC}"
    echo ""
}

print_step() {
    echo ""
    echo -e "${GREEN}▶ $1${NC}"
}

print_header "Cloudflare Tunnel Setup"

echo "This script will help you set up Cloudflare Tunnel for secure remote access."
echo ""
echo "Prerequisites:"
echo "  • A Cloudflare account (free tier works)"
echo "  • A domain added to Cloudflare"
echo ""

# Check if cloudflared is installed
if ! command -v cloudflared &> /dev/null; then
    print_step "Installing cloudflared..."
    
    # Detect architecture
    ARCH=$(uname -m)
    case $ARCH in
        x86_64)
            ARCH_NAME="amd64"
            ;;
        aarch64|arm64)
            ARCH_NAME="arm64"
            ;;
        armv7l)
            ARCH_NAME="arm"
            ;;
        *)
            echo -e "${RED}Unsupported architecture: $ARCH${NC}"
            exit 1
            ;;
    esac
    
    # Download and install
    if command -v apt &> /dev/null; then
        # Debian/Ubuntu
        curl -L "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${ARCH_NAME}.deb" -o /tmp/cloudflared.deb
        sudo dpkg -i /tmp/cloudflared.deb
        rm /tmp/cloudflared.deb
    elif command -v dnf &> /dev/null; then
        # Fedora/RHEL
        curl -L "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${ARCH_NAME}.rpm" -o /tmp/cloudflared.rpm
        sudo dnf install -y /tmp/cloudflared.rpm
        rm /tmp/cloudflared.rpm
    else
        # Generic binary install
        curl -L "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${ARCH_NAME}" -o /tmp/cloudflared
        sudo mv /tmp/cloudflared /usr/local/bin/
        sudo chmod +x /usr/local/bin/cloudflared
    fi
    
    echo -e "${GREEN}✓ cloudflared installed${NC}"
else
    echo -e "${GREEN}✓ cloudflared is already installed${NC}"
    cloudflared --version
fi

# Check for existing authentication
print_step "Checking Cloudflare authentication..."

if [ -f "$CLOUDFLARED_CONFIG_DIR/cert.pem" ]; then
    echo -e "${GREEN}✓ Already authenticated with Cloudflare${NC}"
else
    echo "You need to authenticate with Cloudflare."
    echo "This will open a browser window."
    echo ""
    read -p "Press Enter to continue..."
    
    cloudflared tunnel login
    
    if [ -f "$CLOUDFLARED_CONFIG_DIR/cert.pem" ]; then
        echo -e "${GREEN}✓ Authentication successful${NC}"
    else
        echo -e "${RED}Authentication failed. Please try again.${NC}"
        exit 1
    fi
fi

# List existing tunnels
print_step "Checking existing tunnels..."

EXISTING_TUNNELS=$(cloudflared tunnel list 2>/dev/null | grep -v "ID" | grep -v "^$" || true)

if [ -n "$EXISTING_TUNNELS" ]; then
    echo "Existing tunnels:"
    echo "$EXISTING_TUNNELS"
    echo ""
    read -p "Create a new tunnel? (Y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        read -p "Enter existing tunnel name to use: " TUNNEL_NAME
    else
        TUNNEL_NAME=""
    fi
fi

# Create tunnel if needed
if [ -z "$TUNNEL_NAME" ]; then
    print_step "Creating new tunnel..."
    
    read -p "Enter tunnel name (default: bike-tracker): " TUNNEL_NAME
    TUNNEL_NAME=${TUNNEL_NAME:-bike-tracker}
    
    cloudflared tunnel create "$TUNNEL_NAME"
    
    echo -e "${GREEN}✓ Tunnel '$TUNNEL_NAME' created${NC}"
fi

# Get tunnel ID
TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')

if [ -z "$TUNNEL_ID" ]; then
    echo -e "${RED}Could not find tunnel ID for '$TUNNEL_NAME'${NC}"
    exit 1
fi

echo "Tunnel ID: $TUNNEL_ID"

# Configure DNS
print_step "Configuring DNS..."

read -p "Enter subdomain for the service (e.g., bike-api): " SUBDOMAIN
read -p "Enter your domain (e.g., example.com): " DOMAIN

HOSTNAME="${SUBDOMAIN}.${DOMAIN}"

echo ""
echo "This will create a DNS record: $HOSTNAME → tunnel"
read -p "Continue? (Y/n) " -n 1 -r
echo

if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME"
    echo -e "${GREEN}✓ DNS record created for $HOSTNAME${NC}"
fi

# Create config file
print_step "Creating tunnel configuration..."

mkdir -p "$CLOUDFLARED_CONFIG_DIR"

cat > "$CLOUDFLARED_CONFIG_DIR/config.yml" << EOF
# Cloudflare Tunnel Configuration
# Generated by setup-cloudflare.sh on $(date)

tunnel: $TUNNEL_ID
credentials-file: $CLOUDFLARED_CONFIG_DIR/${TUNNEL_ID}.json

ingress:
  # Bike Power Tracker API
  - hostname: $HOSTNAME
    service: http://localhost:8080
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
      
  # Catch-all (required)
  - service: http_status:404
EOF

echo -e "${GREEN}✓ Configuration saved to $CLOUDFLARED_CONFIG_DIR/config.yml${NC}"

# Get tunnel token for Docker
print_step "Getting tunnel token for Docker..."

echo ""
echo "To run the tunnel in Docker, you need the tunnel token."
echo "You can get it from the Cloudflare Zero Trust dashboard:"
echo ""
echo "  1. Go to https://one.dash.cloudflare.com"
echo "  2. Navigate to: Networks → Tunnels"
echo "  3. Click on your tunnel ($TUNNEL_NAME)"
echo "  4. Click 'Configure'"
echo "  5. Copy the token from the 'Install connector' section"
echo ""

read -p "Enter tunnel token (or press Enter to skip): " TUNNEL_TOKEN

if [ -n "$TUNNEL_TOKEN" ]; then
    # Update .env file
    if [ -f "$SERVICE_DIR/.env" ]; then
        if grep -q "CLOUDFLARE_TUNNEL_TOKEN" "$SERVICE_DIR/.env"; then
            sed -i "s|CLOUDFLARE_TUNNEL_TOKEN=.*|CLOUDFLARE_TUNNEL_TOKEN=$TUNNEL_TOKEN|" "$SERVICE_DIR/.env"
        else
            echo "" >> "$SERVICE_DIR/.env"
            echo "# Cloudflare Tunnel" >> "$SERVICE_DIR/.env"
            echo "CLOUDFLARE_TUNNEL_TOKEN=$TUNNEL_TOKEN" >> "$SERVICE_DIR/.env"
        fi
        echo -e "${GREEN}✓ Token saved to .env${NC}"
    fi
fi

# Option to install as system service
print_step "Install as system service?"

echo ""
echo "You can run the tunnel as:"
echo "  1. Docker container (recommended for home deployment)"
echo "  2. System service (runs independently of Docker)"
echo ""
read -p "Install as system service? (y/N) " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    sudo cloudflared service install
    sudo systemctl enable cloudflared
    sudo systemctl start cloudflared
    
    echo ""
    echo -e "${GREEN}✓ Cloudflare tunnel installed as system service${NC}"
    echo ""
    echo "Service commands:"
    echo "  sudo systemctl status cloudflared"
    echo "  sudo systemctl restart cloudflared"
    echo "  sudo journalctl -u cloudflared -f"
fi

# Summary
print_header "Setup Complete!"

echo "Your Bike Power Tracker is now accessible at:"
echo ""
echo -e "  ${GREEN}https://$HOSTNAME${NC}"
echo ""
echo "Configuration files:"
echo "  • Tunnel config: $CLOUDFLARED_CONFIG_DIR/config.yml"
echo "  • Credentials: $CLOUDFLARED_CONFIG_DIR/${TUNNEL_ID}.json"
if [ -n "$TUNNEL_TOKEN" ]; then
    echo "  • Token saved to: $SERVICE_DIR/.env"
fi
echo ""
echo "To start the tunnel with Docker:"
echo "  docker compose -f docker-compose.home.yml --profile cloudflare up -d"
echo ""
echo "To test the tunnel manually:"
echo "  cloudflared tunnel run $TUNNEL_NAME"
echo ""
echo "Documentation: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/"
